# Generated by Django 5.2.13 on 2026-07-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('DEFAULT', 'Default'), ('TECH', 'Tech'), ('SPORTS', 'Sports'), ('FURNITURE', 'Furniture'), ('FASHION', 'Fasion'), ('TOYS', 'Toys'), ('HOME', 'Home')], default='DefaulT'),
        ),
    ]
