# Generated by Django 5.2.13 on 2026-07-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('DEFAULT', 'Default'), ('TECH', 'Tech'), ('SPORTS', 'Sports'), ('FURNITURE', 'Furniture'), ('FASHION', 'Fashion'), ('TOYS', 'Toys'), ('HOME', 'Home')], default=('DEFAULT', 'Default')),
        ),
    ]
