# Generated by Django 5.2.13 on 2026-07-13 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_remove_watchlist_user_watchlist_listings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='listings',
        ),
    ]
