# Generated by Django 5.2.13 on 2026-07-13 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_remove_watchlist_listings'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='listings',
            field=models.ManyToManyField(to='auctions.listing'),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
