# Generated by Django 5.2.13 on 2026-07-15 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_remove_bid_listing_bid_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='starting_value',
            new_name='value',
        ),
    ]
