# Generated by Django 5.2.13 on 2026-07-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_rename_starting_value_listing_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='current_bid',
            field=models.PositiveIntegerField(default='1'),
        ),
    ]
