# Generated by Django 5.2.13 on 2026-07-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_alter_bid_current_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='current_bid',
            field=models.PositiveIntegerField(),
        ),
    ]
