# Generated by Django 5.2.13 on 2026-07-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_alter_listing_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('DEFAULT', 'Default'), ('ELECTRONICS', 'Electronics'), ('SPORTS', 'Sports'), ('FURNITURE', 'Furniture'), ('FASHION', 'Fashion'), ('TOYS', 'Toys'), ('HOME', 'Home')], default=('DEFAULT', 'Default')),
        ),
    ]
