# Generated by Django 5.2.13 on 2026-07-24 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0033_alter_listing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='topBidUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topBidUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default=('OPEN', 'Open')),
        ),
    ]
